#### data.R - Documentation for package datasets ####
##
## All four objects are generated by data-raw/generate_examples.R (set.seed(2024)).
## bglm_data / bglmm_data are the raw simulated datasets;
## bglm_fit  / bglmm_fit  are pre-computed model fits used in examples.

# ── Raw datasets ──────────────────────────────────────────────────────────────

#' Simulated Single-Level Clinical Trial Data
#'
#' A simulated dataset representing a two-arm clinical trial with 200
#' subjects, one continuous covariate, and two binary outcomes. It serves
#' as the underlying data for \code{\link{bglm_fit}} and can be used to
#' illustrate \code{\link{bglm}}.
#'
#' @format A data frame with 200 rows and 4 columns:
#' \describe{
#'   \item{group}{Character. Treatment arm: \code{"placebo"} (n = 100) or
#'     \code{"drug"} (n = 100).}
#'   \item{age}{Numeric. Continuous covariate drawn from
#'     \eqn{N(50,\,10^2)}.}
#'   \item{y1}{Integer (0/1). First binary outcome.}
#'   \item{y2}{Integer (0/1). Second binary outcome.}
#' }
#'
#' @details
#' Data were generated with \code{set.seed(2024)} using logistic models:
#' \deqn{
#'   P(y_1 = 1) = \text{logit}^{-1}(-0.50 + 0.75\,\text{drug}
#'                + 0.10\,\text{age}/10)
#' }
#' \deqn{
#'   P(y_2 = 1) = \text{logit}^{-1}(-0.50 + 0.80\,\text{drug}
#'                + 0.05\,\text{age}/10)
#' }
#' where \code{drug} is 1 for the drug arm and 0 for placebo.
#' See \code{data-raw/generate_examples.R} for the full script.
#'
#' @examples
#' head(bglm_data)
#' table(bglm_data$group, bglm_data$y1)
#'
#' @seealso \code{\link{bglm}}, \code{\link{bglm_fit}}, \code{\link{bglmm_data}}
"bglm_data"


#' Simulated Multilevel Clinical Trial Data
#'
#' A simulated dataset representing a two-arm clinical trial with 300
#' subjects nested within 20 clusters (e.g., hospitals), one continuous
#' covariate, and two binary outcomes. It serves as the underlying data
#' for \code{\link{bglmm_fit}} and can be used to illustrate
#' \code{\link{bglmm}}.
#'
#' @format A data frame with 300 rows and 5 columns:
#' \describe{
#'   \item{id}{Factor with 20 levels (\code{1}--\code{20}). Cluster
#'     identifier (e.g., hospital). Each cluster contains 15 subjects.}
#'   \item{group}{Character. Treatment arm: \code{"placebo"} (clusters
#'     1--10) or \code{"drug"} (clusters 11--20).}
#'   \item{age}{Numeric. Continuous covariate drawn from
#'     \eqn{N(50,\,10^2)}.}
#'   \item{y1}{Integer (0/1). First binary outcome.}
#'   \item{y2}{Integer (0/1). Second binary outcome.}
#' }
#'
#' @details
#' Data were generated with \code{set.seed(2024)} using logistic models
#' with cluster-specific random intercepts
#' \eqn{u_{j1},\,u_{j2} \sim N(0,\,0.25)}:
#' \deqn{
#'   P(y_1 = 1) = \text{logit}^{-1}(-0.50 + 0.75\,\text{drug}
#'                + 0.10\,\text{age}/10 + u_{j1})
#' }
#' \deqn{
#'   P(y_2 = 1) = \text{logit}^{-1}(-0.50 + 0.80\,\text{drug}
#'                + 0.05\,\text{age}/10 + u_{j2})
#' }
#' where \code{drug} is 1 for the drug arm and 0 for placebo.
#' See \code{data-raw/generate_examples.R} for the full script.
#'
#' @examples
#' head(bglmm_data)
#' table(bglmm_data$group, bglmm_data$id)
#'
#' @seealso \code{\link{bglmm}}, \code{\link{bglmm_fit}}, \code{\link{bglm_data}}
"bglmm_data"


# ── Pre-computed model fits ───────────────────────────────────────────────────

#' Pre-computed bglm Example Fit
#'
#' A fitted \code{\link{bglm}} object estimated on \code{\link{bglm_data}}.
#' Used in package examples and tests so that \code{print}, \code{summary},
#' and \code{plot} examples run in well under 5 seconds without re-running
#' the MCMC sampler.
#'
#' @format An object of class \code{bglm} as returned by \code{\link{bglm}}.
#'   See the \strong{Value} section of \code{\link{bglm}} for a full
#'   description of the list components. Key settings:
#'   \code{n_burn = 10000}, \code{n_it = 20000}, \code{n_chain = 2},
#'   \code{return_diagnostics = TRUE}, \code{return_samples = TRUE}.
#'
#' @details
#' Generated with \code{set.seed(2024)}.
#' See \code{data-raw/generate_examples.R} for the full reproducible script.
#'
#' @examples
#' print(bglm_fit)
#' summary(bglm_fit)
#'
#' @seealso \code{\link{bglm}}, \code{\link{bglm_data}}, \code{\link{bglmm_fit}}
"bglm_fit"


#' Pre-computed bglmm Example Fit
#'
#' A fitted \code{\link{bglmm}} object estimated on \code{\link{bglmm_data}}.
#' Used in package examples and tests so that \code{print}, \code{summary},
#' and \code{plot} examples run in well under 5 seconds without re-running
#' the MCMC sampler.
#'
#' @format An object of class \code{bglmm} as returned by \code{\link{bglmm}}.
#'   See the \strong{Value} section of \code{\link{bglmm}} for a full
#'   description of the list components. Key settings:
#'   \code{n_burn = 10000}, \code{n_it = 50000}, \code{n_thin = 10},
#'   \code{n_chain = 2}, \code{return_diagnostics = TRUE},
#'   \code{return_samples = TRUE}.
#'
#' @details
#' Generated with \code{set.seed(2024)}.
#' See \code{data-raw/generate_examples.R} for the full reproducible script.
#'
#' @examples
#' print(bglmm_fit)
#' summary(bglmm_fit)
#'
#' @seealso \code{\link{bglmm}}, \code{\link{bglmm_data}}, \code{\link{bglm_fit}}
"bglmm_fit"
